const studentData = [
  {
    key: "1",
    name: "Nguyễn Thị Phương Anh",
    gender: "Nữ",
    dob: "2007-01-01",
    address: "",
    class: "12A1",
  },
  {
    key: "2",
    name: "Dương Thị Bảo Châu",
    gender: "Nữ",
    dob: "2007-02-01",
    address: "",
    class: "12A1",
  },
  {
    key: "3",
    name: "Nguyễn Quốc Đạt",
    gender: "Nam",
    dob: "2007-03-01",
    address: "",
    class: "12A1",
  },
  {
    key: "4",
    name: "Phạm Minh Đức",
    gender: "Nam",
    dob: "2007-04-01",
    address: "",
    class: "12A1",
  },
  {
    key: "5",
    name: "Vũ Minh Đức",
    gender: "Nam",
    dob: "2007-05-01",
    address: "",
    class: "12A1",
  },
  {
    key: "6",
    name: "Đinh Đức Hải",
    gender: "Nam",
    dob: "2007-06-01",
    address: "",
    class: "12A1",
  },
  {
    key: "7",
    name: "Phạm Lê Thị Thiên Hân",
    gender: "Nữ",
    dob: "2007-07-01",
    address: "",
    class: "12A1",
  },
  {
    key: "8",
    name: "Hoàng Mai Hiền",
    gender: "Nữ",
    dob: "2007-08-01",
    address: "",
    class: "12A1",
  },
  {
    key: "9",
    name: "Bùi Nguyễn Minh Khôi",
    gender: "Nam",
    dob: "2007-09-01",
    address: "",
    class: "12A1",
  },
  {
    key: "10",
    name: "Võ Nữ Hồng Loan",
    gender: "Nữ",
    dob: "2007-10-01",
    address: "",
    class: "12A1",
  },
  {
    key: "11",
    name: "Phan Nhật Nam",
    gender: "Nam",
    dob: "2007-11-01",
    address: "",
    class: "12A1",
  },
  {
    key: "12",
    name: "Huỳnh Tấn Phát",
    gender: "Nam",
    dob: "2007-12-01",
    address: "",
    class: "12A1",
  },
  {
    key: "13",
    name: "Lê Nguyên Phúc",
    gender: "Nam",
    dob: "2007-01-02",
    address: "",
    class: "12A1",
  },
  {
    key: "14",
    name: "Hoàng Minh Quân",
    gender: "Nam",
    dob: "2007-02-02",
    address: "",
    class: "12A1",
  },
  {
    key: "15",
    name: "Ngô Ngọc Qúy",
    gender: "Nam",
    dob: "2007-03-02",
    address: "",
    class: "12A1",
  },
  {
    key: "16",
    name: "Tôn Thất Minh Sơn",
    gender: "Nam",
    dob: "2007-04-02",
    address: "",
    class: "12A1",
  },
  {
    key: "17",
    name: "Nguyễn Ngọc Minh Tâm",
    gender: "Nam",
    dob: "2007-05-02",
    address: "",
    class: "12A1",
  },
  {
    key: "18",
    name: "Lê Quang Thành",
    gender: "Nam",
    dob: "2007-06-02",
    address: "",
    class: "12A1",
  },
  {
    key: "19",
    name: "Đỗ Thu Thảo",
    gender: "Nữ",
    dob: "2007-07-02",
    address: "",
    class: "12A1",
  },
  {
    key: "20",
    name: "Trần Ngọc Thùy",
    gender: "Nữ",
    dob: "2007-08-02",
    address: "",
    class: "12A1",
  },
  {
    key: "21",
    name: "Phạm Thị Thu Thủy",
    gender: "Nữ",
    dob: "2007-09-02",
    address: "",
    class: "12A1",
  },
  {
    key: "22",
    name: "Lê Minh Triết",
    gender: "Nam",
    dob: "2007-10-02",
    address: "",
    class: "12A1",
  },
  {
    key: "23",
    name: "Phan Anh Tuấn",
    gender: "Nam",
    dob: "2007-11-02",
    address: "",
    class: "12A1",
  },
  {
    key: "24",
    name: "Phan Ngọc Phương Uyên",
    gender: "Nữ",
    dob: "2007-12-02",
    address: "",
    class: "12A1",
  },
  {
    key: "25",
    name: "Thi Tường Vân",
    gender: "Nữ",
    dob: "2007-01-03",
    address: "",
    class: "12A1",
  },
  {
    key: "26",
    name: "Văn Thị Như Ý",
    gender: "Nữ",
    dob: "2007-02-03",
    address: "",
    class: "12A1",
  },
  {
    key: "27",
    name: "Vũ Lê Hoàng",
    gender: "Nam",
    dob: "2007-03-03",
    address: "",
    class: "12A1",
  },
  {
    key: "28",
    name: "Phạm Minh Khôi",
    gender: "Nam",
    dob: "2007-04-03",
    address: "",
    class: "12A1",
  },
  {
    key: "29",
    name: "Nguyễn Lê Minh",
    gender: "Nam",
    dob: "2007-05-03",
    address: "",
    class: "12A1",
  },
  {
    key: "30",
    name: "Nguyễn Trần Minh Hy",
    gender: "Nam",
    dob: "2007-06-03",
    address: "",
    class: "12A1",
  },
];

export default studentData;
